wandb_version: 1

__is_set:
  desc: null
  value:
    blocks_per_epoch: true
    subtensor.network: true
    wallet.name: true
    wandb.on: true
_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1699070452.690879
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 2
      - 13
      - 16
      - 23
      - 24
      4: 3.8.16
      5: 0.13.3
      6: 4.34.1
      8:
      - 5
axon:
  desc: null
  value:
    __is_set: {}
    external_ip: null
    external_port: null
    ip: '[::]'
    max_workers: 10
    port: 8091
blocks_per_epoch:
  desc: null
  value: 2
config:
  desc: null
  value: null
device:
  desc: null
  value: cuda
full_path:
  desc: null
  value: /home/setup/.bittensor/miners/foundation/default/netuidNone/validator
hotkey:
  desc: null
  value: 5F4tQyWrhfGVcNhoqeiNsR6KjD4wMZ2kfhLj4oHYuyHbZAc3
logging:
  desc: null
  value:
    __is_set: {}
    debug: false
    logging_dir: ~/.bittensor/miners
    record_log: false
    trace: false
no_prompt:
  desc: null
  value: false
no_version_checking:
  desc: null
  value: false
run_name:
  desc: null
  value: validator-249-0OV3XK1QT3
strict:
  desc: null
  value: false
subtensor:
  desc: null
  value:
    __is_set: {}
    _mock: false
    chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
    network: local
uid:
  desc: null
  value: 249
wallet:
  desc: null
  value:
    __is_set: {}
    hotkey: default
    name: foundation
    path: ~/.bittensor/wallets/
wandb:
  desc: null
  value:
    __is_set: {}
    'on': true
